### ISSUE TITLE
Need more tests

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/ProdirectScraper#1]
Currently I got tests only for helpers class. PR's with tests for other implementations are welcome

**Comment by mayela** [comment]
I'm trying to run the project on local for work on test but I had problems with the PyOpenSSL version and python version. With your code I deduced that the Python version is 2.7, right?

**Comment by ZoranPandovski** [comment]
Hi @mayela, yes it was written with 2.7.12 python version. If you still getting error please share it with me
