### ISSUE TITLE
Resolve vulnerabilities issues

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/ProdirectScraper#16]
https://snyk.io/test/github/ZoranPandovski/ProdirectScraper?targetFile=requirements.txt

Some of the requirements libraries should be updated to the latest available version.

**Comment by vinschess** [comment]
I am working on this.

**Comment by vinschess** [comment]
Add PR with [#20](https://github.com/ZoranPandovski/ProdirectScraper/pull/20)

**Comment by ZoranPandovski** [comment]
Thanks
